package com.buetcrt.csefest.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.buetcrt.csefest.dao.Products;

import com.buetcrt.csefest.dao.ProductsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productsDaoConfig;

    private final ProductsDao productsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productsDaoConfig = daoConfigMap.get(ProductsDao.class).clone();
        productsDaoConfig.initIdentityScope(type);

        productsDao = new ProductsDao(productsDaoConfig, this);

        registerDao(Products.class, productsDao);
    }
    
    public void clear() {
        productsDaoConfig.getIdentityScope().clear();
    }

    public ProductsDao getProductsDao() {
        return productsDao;
    }

}
